# Generated by Django 4.1.1 on 2022-10-14 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('no_of_pending_tasks', models.IntegerField(default=0)),
                ('no_of_tasks_completed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='team_leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_project_created', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='team_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('total_points', models.IntegerField(default=0)),
                ('is_team_assigned', models.BooleanField(default=False)),
                ('team_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamleader.team_leader')),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('points', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamleader.team_member')),
                ('task_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamleader.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_teamleader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teamleader.team_leader'),
        ),
    ]
